s1_cifar10_dp:
        init_channels: 36
        layers: 20
s1_cifar10_wd:
        init_channels: 36
        layers: 20
s1_cifar100_dp:
        init_channels: 16
        layers: 8
s1_cifar100_wd:
        init_channels: 16
        layers: 8
s1_svhn_dp:
        init_channels: 16
        layers: 8
s1_svhn_wd:
        init_channels: 16
        layers: 8
s2_cifar10_dp:
        init_channels: 16
        layers: 20
s2_cifar10_wd:
        init_channels: 16
        layers: 8
s2_cifar100_dp:
        init_channels: 16
        layers: 8
s2_cifar100_wd:
        init_channels: 16
        layers: 8
s2_svhn_dp:
        init_channels: 16
        layers: 8
s2_svhn_wd:
        init_channels: 16
        layers: 8
s3_cifar10_dp:
        init_channels: 36
        layers: 20
s3_cifar10_wd:
        init_channels: 16
        layers: 8
s3_cifar100_dp:
        init_channels: 16
        layers: 8
s3_cifar100_wd:
        init_channels: 16
        layers: 8
s3_svhn_dp:
        init_channels: 16
        layers: 8
s3_svhn_wd:
        init_channels: 16
        layers: 8
s4_cifar10_dp:
        init_channels: 16
        layers: 20
s4_cifar10_wd:
        init_channels: 16
        layers: 8
s4_cifar100_dp:
        init_channels: 16
        layers: 8
s4_cifar100_wd:
        init_channels: 16
        layers: 8
s4_svhn_dp:
        init_channels: 16
        layers: 8
s4_svhn_wd:
        init_channels: 16
        layers: 8

